// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGidTvtYiLF0NdZE6M1L5SGkhVmXyp58E',
    appId: '1:353303140418:web:c81f269ff4ebc2a166f5db',
    messagingSenderId: '353303140418',
    projectId: 'carpooling-cd075',
    authDomain: 'carpooling-cd075.firebaseapp.com',
    storageBucket: 'carpooling-cd075.firebasestorage.app',
    measurementId: 'G-G24GYMEB95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmt4YxCMzibe385K5-k1hUB8YD3pqie4',
    appId: '1:353303140418:android:b95ee42236bc199b66f5db',
    messagingSenderId: '353303140418',
    projectId: 'carpooling-cd075',
    storageBucket: 'carpooling-cd075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDudnqWf0GWjcaK3k3PcOmDuqK_HZutdzw',
    appId: '1:353303140418:ios:b0288a0be22d4e7f66f5db',
    messagingSenderId: '353303140418',
    projectId: 'carpooling-cd075',
    storageBucket: 'carpooling-cd075.firebasestorage.app',
    iosBundleId: 'com.example.carpooling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDudnqWf0GWjcaK3k3PcOmDuqK_HZutdzw',
    appId: '1:353303140418:ios:b0288a0be22d4e7f66f5db',
    messagingSenderId: '353303140418',
    projectId: 'carpooling-cd075',
    storageBucket: 'carpooling-cd075.firebasestorage.app',
    iosBundleId: 'com.example.carpooling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGidTvtYiLF0NdZE6M1L5SGkhVmXyp58E',
    appId: '1:353303140418:web:3ae0ad2de6fc7a3866f5db',
    messagingSenderId: '353303140418',
    projectId: 'carpooling-cd075',
    authDomain: 'carpooling-cd075.firebaseapp.com',
    storageBucket: 'carpooling-cd075.firebasestorage.app',
    measurementId: 'G-9WVDSHBX9K',
  );
}
