name: Flutter Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter test test/route_service_test.dart

      - name: Run integration tests on Android emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: Nexus 6
          script: |
            flutter drive \
              --driver=test_driver/integration_test.dart \
              --target=integration_test/app_test.dart